language: csharp
dist: bionic
language: csharp
mono: none
dotnet: 3.1.403
solution: InstaSharper.sln

script:
  - cd InstaSharper
  - dotnet --info
  - dotnet restore
  - dotnet build  -c release
  - dotnet test InstaSharper.Tests/InstaSharper.Tests.csproj --filter TestCategory=AlwaysRun
  - dotnet pack -c release InstaSharper/InstaSharper.csproj -o npkgs
  - dotnet pack -c release InstaSharper.Abstractions/InstaSharper.Abstractions.csproj -o npkgs
  - dotnet clean
